FROM postgres:alpine

ENV REQUEST_ID=$REQUEST_ID
ENV POSTGRES_PASSWORD=password
ENV LOGS_FOLDER=/var/lib/postgresql/datapg_log
ENV LOGS_LEVEL=$LOGS_LEVEL

COPY ["scripts/postgres.startup.sh", "docker-entrypoint-initdb.d/"]
COPY ["scripts/app", "."]

RUN apk add --update python3 py3-pip npm
RUN npm i forever ts-node -g
RUN npm i
